### ISSUE TITLE
Documentation Clarification

### ISSUE THREAD

**Issue by Drog1744** [zdurham/s3-upload-github-action#1]
I see a requirement for an S3 key to be stored in github secrets. Where does that map to in s3? or in other words do you know where I would find the s3 key in AWS?

**Comment by zdurham** [comment]
Hello! Thanks for submitting an issue!

The S3_KEY (termed in AWS usually as _object key_) is a unique identifier for your data in the specified bucket. An example key might be `lambda.zip`. Usually they match whatever the name of the object you're uploading is. So later if you want to download the file from S3, you'd `GET` on http://your-bucket-name.s3.amazonaws.com/lambda.zip.

It's not necessary to store it as a secret, but sometimes it can be  advantageous to hide your object keys.

More on S3 keys here: https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html
